version: '3.3'

services:
  bot:
    container_name: "${BOT_NAME:-tg_bot-container}"
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - botnet
    depends_on:
      - db
  db:
    image: "sameersbn/postgresql:10-2"
    container_name: "database"
    evironment:
      DB_USER: $DB_USER
      PG_PASSWORD: $PG_PASSWORD
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
      DB_HOST: $DB_HOST
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./pgdata:/var/lib/postgresql


networks:
  botnet:
    driver: bridge