version: '3.8'

services:
  bot:
    env_file: .env
    container_name: "${BOT_NAME:-bot}"
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-bot}
    command: python -m bot
    restart: unless-stopped
    networks:
      - botnet
    depends_on:
      - redis
      - database
  redis:
    image: redis:7.0-rc-alpine
    env_file: .env
    container_name: "${BOT_NAME:-redis}"
    volumes:
      - "./redis.conf:/usr/local/etc/redis"
      - "./redis_data:/data"
    command: "redis-server /usr/local/etc/redis --requirepass ${REDIS_PASS}"
    ports:
      - 6379:6379
    restart: "unless-stopped"
    networks:
      - botnet
  database:
    image: "postgres:14.2-alpine"
    container_name: "${BOT_NAME:-db}"
    volumes:
      - ./pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: $DB_LOGIN
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - botnet

networks:
  botnet:
    driver: bridge