"""initdb

Revision ID: 769ee5c99617
Revises: 
Create Date: 2022-03-15 18:26:05.125560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769ee5c99617'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
