"""empty message

Revision ID: ae1b049106a3
Revises: ee9ec1b9bfe4
Create Date: 2022-03-15 18:47:38.024850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1b049106a3'
down_revision = 'ee9ec1b9bfe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trash',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('User', sa.Column('id', sa.BigInteger(), nullable=False))
    op.add_column('User', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('User', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('user_id', sa.BIGINT(), server_default=sa.text('nextval(\'"User_user_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('User', 'status')
    op.drop_column('User', 'id')
    op.drop_table('Trash')
    # ### end Alembic commands ###
